---
  openapi: "3.0.0"
  info:
    title: "Free & Finally tagless exploration"
    description: "Free & Finally Tagless exploration"
    version: "1.0.0"
  consumes:
    - application/json
  produces:
    - application/json
